kind: Service
apiVersion: v1

metadata:
  name: nexus-service
  namespace: usine-logicielle

spec:
  type: LoadBalancer
  ports:
    - name: web-ui
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: nexus
